import logging
from typing import Dict, Any, List
from langchain_core.messages import SystemMessage, HumanMessage
from ..models.schemas import AppState, ExecutionStatus, ExecutionResult, PermissionAction
from .base import local_llm
from ..tools.mcp_client import mcp_gateway
from ..permissions.manager import permission_manager

logger = logging.getLogger("sugio_labs.agents.coding_agent")

class CodingAgent:
    def __init__(self):
        self.system_prompt = (
            "You are a Safe Coding Agent. "
            "Your job is to execute ONE step of an ExecutionPlan. "
            "You will be given the step details. "
            "Generate the necessary code changes and request actions using the provided safe tools. "
            "If you need to write a file, output a structured representation that our system can parse, or use the MCP fs tools."
        )

    async def process(self, state: AppState) -> AppState:
        if state.get("execution_approval_status") != "APPROVED":
            logger.warning("CodingAgent invoked without explicit execution approval!")
            return state
            
        plan = state.get("execution_plan")
        idx = state.get("current_step_index", 0)
        
        if not plan or idx >= len(plan.ordered_steps):
            return state
            
        step = plan.ordered_steps[idx]
        logger.info(f"CodingAgent processing step {idx+1}/{len(plan.ordered_steps)}: {step.title}")
        
        step.status = ExecutionStatus.IN_PROGRESS
        
        # Here we would actually invoke the LLM to write the code.
        # But for safety, the agent itself requests permissions to execute writes/commands.
        # To simulate the coding agent executing a safe tool via permission manager:
        
        if step.requires_permission and step.files_to_modify:
            # Request permission for writing files
            perm_req = await permission_manager.request_permission(
                action=PermissionAction.WRITE_FILE,
                target=", ".join(step.files_to_modify),
                details={"step_id": step.id, "title": step.title},
                risk_level=step.risk_level,
                project_id=state.get("session_id")
            )
            
            # Since the graph must pause and wait for UI approval of this specific action if it wasn't pre-approved
            # For this MVP step, we assume the graph will just log it and if we were actually blocking here
            # we would interrupt the graph. But we are relying on ALLOW_FOR_PROJECT from the earlier gates in most cases.
            
            if not permission_manager.is_action_permitted(PermissionAction.WRITE_FILE, perm_req.target, state.get("session_id")):
                step.status = ExecutionStatus.WAITING_PERMISSION
                return state
        
        # Simulated success (in reality, we would call mcp_gateway to write the files generated by LLM)
        # For tests, we'll assume the LLM proposed good code and it was written safely.
        
        result = ExecutionResult(
            step_id=step.id,
            success=True,
            output=f"Successfully implemented {step.title}"
        )
        
        state["execution_results"].append(result)
        step.status = ExecutionStatus.COMPLETED
        step.result_details = result.output
        
        return state

coding_agent = CodingAgent()
